-- AlterTable
ALTER TABLE `user` MODIFY `dietCalories` INTEGER NULL DEFAULT 2500,
    MODIFY `dietCarbs` INTEGER NULL DEFAULT 200,
    MODIFY `dietFiber` INTEGER NULL DEFAULT 25,
    MODIFY `dietMeals` INTEGER NULL DEFAULT 3,
    MODIFY `dietSnacks` INTEGER NULL DEFAULT 2,
    MODIFY `dietWater` INTEGER NULL DEFAULT 8;
